/**
 * Shopify adapter (Admin GraphQL API, default version 2026-10).
 *
 * See docs/research/research-shopify.md for the API facts this relies on.
 *
 * What it writes:
 *  - product / collection SEO title + description via `productUpdate(product:)` / `collectionUpdate(collection:)`
 *  - page / article / blog SEO title + description via the `global.title_tag` / `global.description_tag`
 *    metafields (metafieldsSet with compareDigest)
 *  - noindex via the `seo.hidden` metafield (value "1", number_integer); index again = delete it
 *  - product media alt text via `fileUpdate` (only `id` + `alt`, never `referencesToRemove`)
 *  - redirects via `urlRedirectCreate/Update/Delete`
 *  - JSON-LD as an array of schema objects in metafield `seo_agent.jsonld` (type json) on the resource
 *    (or on the shop for "/"), printed by integrations/shopify/seo-agent-jsonld.liquid
 *  - page / article body find-and-replace (exactly one occurrence)
 *
 * Everything else (h1 = product name, slug, canonical, og tags, robots.txt, llms.txt, hreflang,
 * homepage title/description, internal links) is manual: it lives in the theme or changes
 * merchant-facing data in ways we don't automate.
 */
import type {
  ApplyResult,
  ChangeRecord,
  ChangeType,
  ConnectionResult,
  ResourceKind,
  ResourceRef,
  SiteAdapter,
} from "../schema";
import type { AdapterContext } from "./index";

// ------------------------------------------------------------------ constants

export const SHOPIFY_DEFAULT_API_VERSION = "2026-10";
export const JSONLD_NAMESPACE = "seo_agent";
export const JSONLD_KEY = "jsonld";
export const SNIPPET_MARKER = "seo-agent-jsonld";

/** All types this adapter can apply somewhere on a Shopify store. */
export const SHOPIFY_CAPABILITIES: ChangeType[] = [
  "title",
  "meta_description",
  "robots_meta",
  "image_alt",
  "redirect",
  "jsonld_add",
  "jsonld_fix",
  "content_edit",
];

/** Why each unsupported type stays manual on Shopify. */
export const SHOPIFY_MANUAL_REASONS: Partial<Record<ChangeType, string>> = {
  h1: "On Shopify the H1 is the product/collection/page title; changing it renames the item for customers (manual).",
  canonical: "Canonical tags are printed by the theme (layout/theme.liquid); theme file writes need a Shopify exemption (manual).",
  og_tags: "Open Graph tags come from the theme's social-meta snippet (manual theme edit).",
  robots_txt: "robots.txt is customised via templates/robots.txt.liquid, a theme file (manual).",
  llms_txt: "Shopify cannot serve arbitrary root files like /llms.txt without a theme/app proxy (manual).",
  slug: "Changing a handle changes the URL; never automated.",
  hreflang: "hreflang alternates are generated by Shopify Markets / the theme (manual).",
  internal_link: "Inserting links into body HTML needs editorial judgement (manual).",
  code_change: "Code changes apply to repo sites only.",
};

const REQUIRED_SCOPES: Array<{ anyOf: string[]; why: string }> = [
  { anyOf: ["write_products"], why: "product/collection SEO, metafields and media alt text" },
  { anyOf: ["write_content", "write_online_store_pages"], why: "page/article/blog SEO metafields and body edits" },
  { anyOf: ["write_online_store_navigation"], why: "URL redirects" },
  { anyOf: ["write_files"], why: "image alt text (fileUpdate)" },
  { anyOf: ["read_themes"], why: "auditing theme files (robots.txt.liquid, theme.liquid)" },
];

// ------------------------------------------------------------------ types

export interface ShopifyAdapterOptions {
  /** Injected sleep, for tests. */
  sleep?: (ms: number) => Promise<void>;
  /** Injected clock (ms since epoch), for tests. */
  now?: () => number;
  /** Max attempts for one GraphQL request (throttling / 5xx). Default 6. */
  maxAttempts?: number;
  /** Base delay for exponential backoff in ms. Default 1000. */
  baseDelayMs?: number;
}

type ShopifyKind = "product" | "collection" | "page" | "article" | "blog" | "site";

interface ParsedPath {
  kind: ShopifyKind;
  handle?: string;
  blogHandle?: string;
}

interface MetafieldState {
  id: string;
  value: string;
  type: string;
  compareDigest: string;
}

interface MetafieldSpec {
  namespace: string;
  key: string;
  type: string;
}

/** Rollback data stored in changes.rollback_data. */
export type ShopifyRollback =
  | {
      platform: "shopify";
      op: "seo_field";
      owner: string;
      kind: "product" | "collection";
      field: "title" | "description";
      previous: string | null;
      written: string;
    }
  | {
      platform: "shopify";
      op: "metafield";
      owner: string;
      kind: ShopifyKind;
      namespace: string;
      key: string;
      type: string;
      existed: boolean;
      previous: string | null;
      previous_digest: string | null;
      /** Value written by apply; null = apply deleted the metafield. */
      written: string | null;
      written_digest: string | null;
    }
  | {
      platform: "shopify";
      op: "file_alt";
      media_id: string;
      previous: string | null;
      written: string;
    }
  | {
      platform: "shopify";
      op: "redirect";
      action: "created" | "updated" | "none";
      id: string;
      path: string;
      previous_target: string | null;
      written_target: string;
    }
  | {
      platform: "shopify";
      op: "body";
      owner: string;
      kind: "page" | "article";
      previous: string;
      written: string;
    };

const META_TITLE: MetafieldSpec = { namespace: "global", key: "title_tag", type: "single_line_text_field" };
const META_DESC: MetafieldSpec = { namespace: "global", key: "description_tag", type: "single_line_text_field" };
const META_HIDDEN: MetafieldSpec = { namespace: "seo", key: "hidden", type: "number_integer" };
const META_JSONLD: MetafieldSpec = { namespace: JSONLD_NAMESPACE, key: JSONLD_KEY, type: "json" };

// ------------------------------------------------------------------ pure helpers (exported for tests/runner)

const RESERVED_SECTIONS = new Set(["products", "collections", "pages", "blogs"]);
const LOCALE_RE = /^[a-z]{2,3}(-[a-z0-9]{2,4})?$/i;

/** Parse a storefront URL or path into the Shopify resource it shows. Null = not an SEO-editable resource. */
export function parseShopifyPath(urlOrPath: string): ParsedPath | null {
  let path: string;
  try {
    path = new URL(urlOrPath, "https://placeholder.invalid").pathname;
  } catch {
    return null;
  }
  const segs = path
    .split("/")
    .filter(Boolean)
    .map((s) => {
      try {
        return decodeURIComponent(s);
      } catch {
        return s;
      }
    });
  // Strip a market/locale prefix such as /en-us or /fr.
  if (segs.length > 0 && LOCALE_RE.test(segs[0]!) && !RESERVED_SECTIONS.has(segs[0]!.toLowerCase())) {
    if (segs.length === 1 || RESERVED_SECTIONS.has(segs[1]!.toLowerCase())) segs.shift();
  }
  if (segs.length === 0) return { kind: "site" };
  const [section, a, b, c] = segs.map((s) => s.toLowerCase());
  switch (section) {
    case "products":
      return a && segs.length === 2 ? { kind: "product", handle: a } : null;
    case "collections":
      if (a && segs.length === 2) return a === "all" ? null : { kind: "collection", handle: a };
      if (a && b === "products" && c && segs.length === 4) return { kind: "product", handle: c };
      return null;
    case "pages":
      return a && segs.length === 2 ? { kind: "page", handle: a } : null;
    case "blogs":
      if (a && segs.length === 2) return { kind: "blog", handle: a };
      if (a && b && b !== "tagged" && segs.length === 3) return { kind: "article", blogHandle: a, handle: b };
      return null;
    default:
      return null;
  }
}

/** Whether a change type can be applied on a resource of this kind. */
export function shopifySupports(type: ChangeType, kind: ShopifyKind): boolean {
  switch (type) {
    case "title":
    case "meta_description":
    case "robots_meta":
      return kind === "product" || kind === "collection" || kind === "page" || kind === "article" || kind === "blog";
    case "image_alt":
      return kind === "product";
    case "redirect":
      return true; // shop-level
    case "jsonld_add":
    case "jsonld_fix":
      return true; // any resource, plus the shop for "/"
    case "content_edit":
      return kind === "page" || kind === "article";
    default:
      return false;
  }
}

/** Normalize an image URL to a comparable file key (basename without size suffix / query). */
export function imageKey(src: string): string {
  let p = src.trim();
  try {
    p = new URL(p, "https://x.invalid").pathname;
  } catch {
    p = p.split("?")[0]!;
  }
  let base = p.split("/").pop() ?? "";
  try {
    base = decodeURIComponent(base);
  } catch {
    /* keep */
  }
  base = base.toLowerCase();
  // Shopify size/crop suffixes: name_800x.jpg, name_800x600.jpg, name_800x600_crop_center.jpg, name@2x.jpg
  base = base.replace(/(_(\d+x\d*|\d*x\d+|pico|icon|thumb|small|compact|medium|large|grande|original|master)(_crop_[a-z]+)?)?(@\dx)?(\.[a-z0-9]+)$/, "$5");
  return base;
}

function schemaTypes(block: unknown): string[] {
  if (!block || typeof block !== "object") return [];
  const t = (block as Record<string, unknown>)["@type"];
  if (typeof t === "string") return [t];
  if (Array.isArray(t)) return t.filter((x): x is string => typeof x === "string");
  return [];
}

function parseJsonldValue(value: string | null): Record<string, unknown>[] {
  if (!value) return [];
  let parsed: unknown;
  try {
    parsed = JSON.parse(value);
  } catch {
    return [];
  }
  if (Array.isArray(parsed)) return parsed.filter((x): x is Record<string, unknown> => !!x && typeof x === "object");
  if (parsed && typeof parsed === "object") return [parsed as Record<string, unknown>];
  return [];
}

const sameText = (a: string | null | undefined, b: string | null | undefined) => (a ?? "").trim() === (b ?? "").trim();
const emptyToNull = (s: string | null | undefined): string | null => (s && s.trim() !== "" ? s : null);

function normalizeShop(shop: string): string {
  let s = shop.trim().replace(/^https?:\/\//i, "").replace(/\/.*$/, "").toLowerCase();
  if (!s.includes(".")) s = `${s}.myshopify.com`;
  return s;
}

function countOccurrences(hay: string, needle: string): number {
  if (!needle) return 0;
  let n = 0;
  let i = hay.indexOf(needle);
  while (i !== -1) {
    n++;
    i = hay.indexOf(needle, i + needle.length);
  }
  return n;
}

export class ShopifyUserError extends Error {
  constructor(
    public readonly operation: string,
    public readonly errors: Array<{ field?: string[] | null; message: string; code?: string | null }>,
  ) {
    super(
      `Shopify ${operation} failed: ` +
        errors.map((e) => `${e.field && e.field.length ? e.field.join(".") + ": " : ""}${e.message}${e.code ? ` (${e.code})` : ""}`).join("; "),
    );
    this.name = "ShopifyUserError";
  }
}

export class ShopifyConcurrentEditError extends Error {
  constructor(what: string) {
    super(
      `${what} was edited in Shopify after the agent read it (most likely by a merchant in the admin). ` +
        `Refusing to overwrite their edit; re-read the page and propose again.`,
    );
    this.name = "ShopifyConcurrentEditError";
  }
}

// ------------------------------------------------------------------ GraphQL documents

const Q = {
  ShopInfo: `query ShopInfo {
    shop { id name myshopifyDomain primaryDomain { url host } plan { publicDisplayName shopifyPlus partnerDevelopment } }
    currentAppInstallation { accessScopes { handle } }
  }`,
  AccessScopes: `query AccessScopes { currentAppInstallation { accessScopes { handle } } }`,
  ShopBasics: `query ShopBasics { shop { id primaryDomain { url } } }`,
  ProductByHandle: `query ProductByHandle($handle: String!) {
    productByIdentifier(identifier: { handle: $handle }) { id handle }
  }`,
  CollectionByHandle: `query CollectionByHandle($handle: String!) {
    collectionByIdentifier(identifier: { handle: $handle }) { id handle }
  }`,
  PagesByHandle: `query PagesByHandle($q: String!) { pages(first: 10, query: $q) { nodes { id handle } } }`,
  ArticlesByHandle: `query ArticlesByHandle($q: String!) {
    articles(first: 25, query: $q) { nodes { id handle blog { id handle } } }
  }`,
  BlogsByHandle: `query BlogsByHandle($q: String!) { blogs(first: 10, query: $q) { nodes { id handle } } }`,
  ProductSeo: `query ProductSeo($id: ID!) { product(id: $id) { id title seo { title description } } }`,
  CollectionSeo: `query CollectionSeo($id: ID!) { collection(id: $id) { id title seo { title description } } }`,
  ProductUpdateSeo: `mutation ProductUpdateSeo($product: ProductUpdateInput!) {
    productUpdate(product: $product) { product { id seo { title description } } userErrors { field message } }
  }`,
  CollectionUpdateSeo: `mutation CollectionUpdateSeo($collection: CollectionUpdateInput!) {
    collectionUpdate(collection: $collection) { collection { id seo { title description } } userErrors { field message } }
  }`,
  MetafieldRead: `query MetafieldRead($id: ID!, $namespace: String!, $key: String!) {
    node(id: $id) { id ... on HasMetafields { metafield(namespace: $namespace, key: $key) { id value type compareDigest } } }
  }`,
  ShopMetafieldRead: `query ShopMetafieldRead($namespace: String!, $key: String!) {
    shop { id metafield(namespace: $namespace, key: $key) { id value type compareDigest } }
  }`,
  MetafieldsSet: `mutation MetafieldsSet($metafields: [MetafieldsSetInput!]!) {
    metafieldsSet(metafields: $metafields) { metafields { id namespace key value compareDigest } userErrors { field message code } }
  }`,
  MetafieldsDelete: `mutation MetafieldsDelete($metafields: [MetafieldIdentifierInput!]!) {
    metafieldsDelete(metafields: $metafields) { deletedMetafields { ownerId namespace key } userErrors { field message } }
  }`,
  ProductMedia: `query ProductMedia($id: ID!) {
    product(id: $id) { id media(first: 100) { nodes { id alt mediaContentType ... on MediaImage { image { url } fileStatus } } } }
  }`,
  FileAlt: `query FileAlt($id: ID!) { node(id: $id) { id ... on MediaImage { alt image { url } fileStatus } } }`,
  FileUpdateAlt: `mutation FileUpdateAlt($files: [FileUpdateInput!]!) {
    fileUpdate(files: $files) { files { id alt } userErrors { field message code } }
  }`,
  RedirectsByPath: `query RedirectsByPath($q: String!) { urlRedirects(first: 50, query: $q) { nodes { id path target } } }`,
  RedirectCreate: `mutation RedirectCreate($urlRedirect: UrlRedirectInput!) {
    urlRedirectCreate(urlRedirect: $urlRedirect) { urlRedirect { id path target } userErrors { field message code } }
  }`,
  RedirectUpdate: `mutation RedirectUpdate($id: ID!, $urlRedirect: UrlRedirectInput!) {
    urlRedirectUpdate(id: $id, urlRedirect: $urlRedirect) { urlRedirect { id path target } userErrors { field message code } }
  }`,
  RedirectDelete: `mutation RedirectDelete($id: ID!) {
    urlRedirectDelete(id: $id) { deletedUrlRedirectId userErrors { field message code } }
  }`,
  BodyRead: `query BodyRead($id: ID!) { node(id: $id) { id ... on Page { body } ... on Article { body } } }`,
  PageUpdateBody: `mutation PageUpdateBody($id: ID!, $page: PageUpdateInput!) {
    pageUpdate(id: $id, page: $page) { page { id body } userErrors { field message code } }
  }`,
  ArticleUpdateBody: `mutation ArticleUpdateBody($id: ID!, $article: ArticleUpdateInput!) {
    articleUpdate(id: $id, article: $article) { article { id body } userErrors { field message code } }
  }`,
} as const;

type OpName = keyof typeof Q;

// ------------------------------------------------------------------ adapter

export function createShopifyAdapter(ctx: AdapterContext, opts: ShopifyAdapterOptions = {}): SiteAdapter {
  if (ctx.secrets.platform !== "shopify") throw new Error("createShopifyAdapter: secrets are not for platform shopify");
  const secrets = ctx.secrets;
  const shop = normalizeShop(secrets.shop);
  const apiVersion = ctx.site.config.shopify_api_version || SHOPIFY_DEFAULT_API_VERSION;
  const endpoint = `https://${shop}/admin/api/${apiVersion}/graphql.json`;
  const doFetch: typeof fetch = ctx.fetch ?? ((...a: Parameters<typeof fetch>) => fetch(...a));
  const sleep = opts.sleep ?? ((ms: number) => new Promise<void>((r) => setTimeout(r, ms)));
  const now = opts.now ?? (() => Date.now());
  const maxAttempts = opts.maxAttempts ?? 6;
  const baseDelay = opts.baseDelayMs ?? 1000;
  const log = ctx.log;

  if (!secrets.access_token && !(secrets.client_id && secrets.client_secret)) {
    throw new Error("Shopify secrets need either access_token or client_id + client_secret");
  }

  // ---------------------------------------------------------------- auth
  let cachedToken: { token: string; expiresAt: number } | null = null;

  async function getToken(): Promise<string> {
    if (secrets.access_token) return secrets.access_token;
    if (cachedToken && now() < cachedToken.expiresAt) return cachedToken.token;
    const body = new URLSearchParams({
      grant_type: "client_credentials",
      client_id: secrets.client_id!,
      client_secret: secrets.client_secret!,
    });
    const res = await doFetch(`https://${shop}/admin/oauth/access_token`, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded", Accept: "application/json" },
      body: body.toString(),
    });
    const text = await res.text();
    if (!res.ok) {
      const hint = /shop_not_permitted/.test(text)
        ? " (client credentials only work for stores in the app's own Dev Dashboard organization; use a custom-distribution app + OAuth for client stores)"
        : "";
      throw new Error(`Shopify client-credentials token request failed: HTTP ${res.status} ${text.slice(0, 300)}${hint}`);
    }
    let json: { access_token?: string; expires_in?: number };
    try {
      json = JSON.parse(text);
    } catch {
      throw new Error("Shopify token endpoint returned non-JSON");
    }
    if (!json.access_token) throw new Error("Shopify token endpoint returned no access_token");
    const ttl = Math.max(0, (json.expires_in ?? 86399) - 300) * 1000; // refresh 5 min early
    cachedToken = { token: json.access_token, expiresAt: now() + ttl };
    log("debug", `shopify: obtained client-credentials token (valid ${Math.round(ttl / 60000)} min)`);
    return json.access_token;
  }

  // ---------------------------------------------------------------- GraphQL client
  let lastThrottle: { currentlyAvailable: number; restoreRate: number; maximumAvailable: number } | null = null;
  let lastApiVersionHeader: string | null = null;

  async function gql<T = any>(op: OpName, variables: Record<string, unknown> = {}): Promise<T> {
    let authRetried = false;
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      // Proactive pacing: if the bucket is nearly empty, wait for it to refill a bit.
      if (lastThrottle && lastThrottle.currentlyAvailable < 50 && lastThrottle.restoreRate > 0) {
        const ms = Math.ceil(((50 - lastThrottle.currentlyAvailable) / lastThrottle.restoreRate) * 1000);
        await sleep(ms);
        lastThrottle = null;
      }
      const token = await getToken();
      let res: Response;
      try {
        res = await doFetch(endpoint, {
          method: "POST",
          headers: { "Content-Type": "application/json", Accept: "application/json", "X-Shopify-Access-Token": token },
          body: JSON.stringify({ query: Q[op], variables, operationName: op }),
        });
      } catch (err) {
        if (attempt + 1 >= maxAttempts) throw err;
        const ms = baseDelay * 2 ** attempt;
        log("warn", `shopify: network error on ${op} (${(err as Error).message}); retrying in ${ms} ms`);
        await sleep(ms);
        continue;
      }
      lastApiVersionHeader = res.headers.get("x-shopify-api-version");
      if (res.status === 401 && !secrets.access_token && !authRetried) {
        cachedToken = null;
        authRetried = true;
        attempt--;
        continue;
      }
      if (res.status === 401 || res.status === 403) {
        const t = await res.text().catch(() => "");
        throw new Error(`Shopify ${op}: HTTP ${res.status} — token invalid, app uninstalled or missing access. ${t.slice(0, 200)}`);
      }
      if (res.status === 429 || res.status >= 500) {
        if (attempt + 1 >= maxAttempts) throw new Error(`Shopify ${op}: HTTP ${res.status} after ${maxAttempts} attempts`);
        const retryAfter = Number(res.headers.get("retry-after"));
        const ms = Math.max(Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1000 : 0, baseDelay * 2 ** attempt);
        log("warn", `shopify: HTTP ${res.status} on ${op}; retrying in ${ms} ms`);
        await sleep(ms);
        continue;
      }
      const text = await res.text();
      let json: {
        data?: T;
        errors?: Array<{ message: string; extensions?: { code?: string } }>;
        extensions?: { cost?: { requestedQueryCost?: number; throttleStatus?: { maximumAvailable: number; currentlyAvailable: number; restoreRate: number } } };
      };
      try {
        json = JSON.parse(text);
      } catch {
        throw new Error(`Shopify ${op}: HTTP ${res.status}, non-JSON response: ${text.slice(0, 200)}`);
      }
      const cost = json.extensions?.cost;
      if (cost?.throttleStatus) lastThrottle = { ...cost.throttleStatus };
      const errors = json.errors ?? [];
      if (errors.some((e) => e.extensions?.code === "THROTTLED")) {
        if (attempt + 1 >= maxAttempts) throw new Error(`Shopify ${op}: still THROTTLED after ${maxAttempts} attempts`);
        const ts = cost?.throttleStatus;
        const need = (cost?.requestedQueryCost ?? 50) - (ts?.currentlyAvailable ?? 0);
        const costMs = ts && ts.restoreRate > 0 ? Math.ceil((need / ts.restoreRate) * 1000) : 0;
        const ms = Math.max(1000, costMs, baseDelay * 2 ** attempt);
        log("warn", `shopify: THROTTLED on ${op}; retrying in ${ms} ms (attempt ${attempt + 1}/${maxAttempts})`);
        lastThrottle = null;
        await sleep(ms);
        continue;
      }
      if (errors.length) {
        const denied = errors.some((e) => e.extensions?.code === "ACCESS_DENIED");
        throw new Error(
          `Shopify ${op} GraphQL error: ${errors.map((e) => e.message).join("; ")}` +
            (denied ? " (the app is missing an access scope — see integrations/shopify/README.md)" : ""),
        );
      }
      if (!res.ok) throw new Error(`Shopify ${op}: HTTP ${res.status}`);
      return json.data as T;
    }
    throw new Error(`Shopify ${op}: gave up after ${maxAttempts} attempts`);
  }

  function checkUserErrors(op: string, errs: Array<{ field?: string[] | null; message: string; code?: string | null }> | undefined, what?: string) {
    if (!errs || errs.length === 0) return;
    if (errs.some((e) => e.code === "STALE_OBJECT" || /compare ?digest|stale|has been modified|was modified/i.test(e.message))) {
      throw new ShopifyConcurrentEditError(what ?? "The value");
    }
    throw new ShopifyUserError(op, errs);
  }

  // ---------------------------------------------------------------- shop basics
  let shopBasics: { id: string; primaryUrl: string } | null = null;
  async function getShop() {
    if (!shopBasics) {
      const d = await gql<{ shop: { id: string; primaryDomain: { url: string } } }>("ShopBasics");
      shopBasics = { id: d.shop.id, primaryUrl: d.shop.primaryDomain?.url ?? `https://${shop}` };
    }
    return shopBasics;
  }

  let scopeCache: string[] | null = null;
  async function grantedScopes(): Promise<string[]> {
    if (!scopeCache) {
      const d = await gql<{ currentAppInstallation: { accessScopes: Array<{ handle: string }> } }>("AccessScopes");
      scopeCache = d.currentAppInstallation.accessScopes.map((s) => s.handle);
    }
    return scopeCache;
  }
  const hasScope = (granted: string[], scope: string) =>
    granted.includes(scope) || (scope.startsWith("read_") && granted.includes("write_" + scope.slice(5)));

  // ---------------------------------------------------------------- resolve
  const quote = (s: string) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

  async function lookup(parsed: ParsedPath): Promise<ResourceRef | null> {
    switch (parsed.kind) {
      case "site": {
        const s = await getShop();
        return { kind: "site", id: s.id };
      }
      case "product": {
        const d = await gql<{ productByIdentifier: { id: string; handle: string } | null }>("ProductByHandle", { handle: parsed.handle });
        return d.productByIdentifier ? { kind: "product", id: d.productByIdentifier.id, handle: d.productByIdentifier.handle } : null;
      }
      case "collection": {
        const d = await gql<{ collectionByIdentifier: { id: string; handle: string } | null }>("CollectionByHandle", { handle: parsed.handle });
        return d.collectionByIdentifier ? { kind: "collection", id: d.collectionByIdentifier.id, handle: d.collectionByIdentifier.handle } : null;
      }
      case "page": {
        const d = await gql<{ pages: { nodes: Array<{ id: string; handle: string }> } }>("PagesByHandle", { q: `handle:${quote(parsed.handle!)}` });
        const hit = d.pages.nodes.find((n) => n.handle === parsed.handle);
        return hit ? { kind: "page", id: hit.id, handle: hit.handle } : null;
      }
      case "article": {
        const d = await gql<{ articles: { nodes: Array<{ id: string; handle: string; blog: { handle: string } | null }> } }>(
          "ArticlesByHandle",
          { q: `handle:${quote(parsed.handle!)}` },
        );
        const hit = d.articles.nodes.find((n) => n.handle === parsed.handle && n.blog?.handle === parsed.blogHandle);
        return hit ? { kind: "article", id: hit.id, handle: hit.handle } : null;
      }
      case "blog": {
        const d = await gql<{ blogs: { nodes: Array<{ id: string; handle: string }> } }>("BlogsByHandle", { q: `handle:${quote(parsed.handle!)}` });
        const hit = d.blogs.nodes.find((n) => n.handle === parsed.handle);
        return hit ? { kind: "blog", id: hit.id, handle: hit.handle } : null;
      }
    }
  }

  async function resolve(url: string, type: ChangeType): Promise<ResourceRef | null> {
    if (type === "redirect") {
      const s = await getShop();
      return { kind: "site", id: s.id };
    }
    const parsed = parseShopifyPath(url);
    if (!parsed) {
      log("debug", `shopify: ${url} is not a product/collection/page/blog/article URL`);
      return null;
    }
    if (!shopifySupports(type, parsed.kind)) {
      log("debug", `shopify: ${type} is not supported on ${parsed.kind} (${url}) — manual`);
      return null;
    }
    const ref = await lookup(parsed);
    if (!ref) log("warn", `shopify: no ${parsed.kind} found for ${url}`);
    return ref;
  }

  async function resourceFor(change: Pick<ChangeRecord, "type" | "target">): Promise<ResourceRef & { id: string; kind: ShopifyKind }> {
    let ref = change.target.resource;
    if (!ref || !ref.id || ref.kind === "unknown") ref = (await resolve(change.target.url, change.type)) ?? undefined;
    if (!ref || !ref.id) {
      const reason = SHOPIFY_MANUAL_REASONS[change.type];
      throw new Error(`manual: ${change.type} cannot be applied to ${change.target.url} on Shopify${reason ? ` — ${reason}` : ""}`);
    }
    const kind = ref.kind as ResourceKind;
    if (!["product", "collection", "page", "article", "blog", "site"].includes(kind)) throw new Error(`Shopify: unexpected resource kind ${kind}`);
    if (!shopifySupports(change.type, kind as ShopifyKind)) {
      throw new Error(`manual: ${change.type} is not supported on a Shopify ${kind}`);
    }
    return ref as ResourceRef & { id: string; kind: ShopifyKind };
  }

  // ---------------------------------------------------------------- metafield helpers
  async function readMetafield(owner: string, kind: ShopifyKind, spec: MetafieldSpec): Promise<MetafieldState | null> {
    if (kind === "site") {
      const d = await gql<{ shop: { metafield: MetafieldState | null } }>("ShopMetafieldRead", { namespace: spec.namespace, key: spec.key });
      return d.shop.metafield;
    }
    const d = await gql<{ node: { metafield?: MetafieldState | null } | null }>("MetafieldRead", { id: owner, namespace: spec.namespace, key: spec.key });
    if (!d.node) throw new Error(`Shopify resource ${owner} not found`);
    return d.node.metafield ?? null;
  }

  async function setMetafield(owner: string, spec: MetafieldSpec, value: string, compareDigest: string | null, what: string) {
    const d = await gql<{ metafieldsSet: { metafields: Array<{ id: string; value: string; compareDigest: string }> | null; userErrors: any[] } }>(
      "MetafieldsSet",
      { metafields: [{ ownerId: owner, namespace: spec.namespace, key: spec.key, type: spec.type, value, compareDigest }] },
    );
    checkUserErrors("metafieldsSet", d.metafieldsSet.userErrors, what);
    const mf = d.metafieldsSet.metafields?.[0];
    if (!mf) throw new Error("Shopify metafieldsSet returned no metafield");
    return mf;
  }

  async function deleteMetafield(owner: string, spec: MetafieldSpec) {
    const d = await gql<{ metafieldsDelete: { userErrors: any[] } }>("MetafieldsDelete", {
      metafields: [{ ownerId: owner, namespace: spec.namespace, key: spec.key }],
    });
    checkUserErrors("metafieldsDelete", d.metafieldsDelete.userErrors);
  }

  /** Write (value) or delete (null) a metafield with compare-and-set, return rollback data. */
  async function writeMetafield(
    ref: { id: string; kind: ShopifyKind },
    spec: MetafieldSpec,
    value: string | null,
    what: string,
  ): Promise<Extract<ShopifyRollback, { op: "metafield" }>> {
    const cur = await readMetafield(ref.id, ref.kind, spec);
    let written_digest: string | null = null;
    if (value === null) {
      if (cur) await deleteMetafield(ref.id, spec);
    } else {
      const mf = await setMetafield(ref.id, spec, value, cur ? cur.compareDigest : null, what);
      written_digest = mf.compareDigest ?? null;
    }
    return {
      platform: "shopify",
      op: "metafield",
      owner: ref.id,
      kind: ref.kind,
      namespace: spec.namespace,
      key: spec.key,
      type: cur?.type ?? spec.type,
      existed: !!cur,
      previous: cur?.value ?? null,
      previous_digest: cur?.compareDigest ?? null,
      written: value,
      written_digest,
    };
  }

  // ---------------------------------------------------------------- SEO field helpers (product/collection)
  async function readSeo(ref: { id: string; kind: ShopifyKind }): Promise<{ title: string | null; description: string | null }> {
    if (ref.kind === "product") {
      const d = await gql<{ product: { seo: { title: string | null; description: string | null } } | null }>("ProductSeo", { id: ref.id });
      if (!d.product) throw new Error(`Shopify product ${ref.id} not found`);
      return { title: emptyToNull(d.product.seo?.title), description: emptyToNull(d.product.seo?.description) };
    }
    const d = await gql<{ collection: { seo: { title: string | null; description: string | null } } | null }>("CollectionSeo", { id: ref.id });
    if (!d.collection) throw new Error(`Shopify collection ${ref.id} not found`);
    return { title: emptyToNull(d.collection.seo?.title), description: emptyToNull(d.collection.seo?.description) };
  }

  async function writeSeo(ref: { id: string; kind: ShopifyKind }, seo: { title?: string; description?: string }) {
    if (ref.kind === "product") {
      const d = await gql<{ productUpdate: { product: { seo: { title: string | null; description: string | null } } | null; userErrors: any[] } }>(
        "ProductUpdateSeo",
        { product: { id: ref.id, seo } },
      );
      checkUserErrors("productUpdate", d.productUpdate.userErrors);
      return d.productUpdate.product?.seo;
    }
    const d = await gql<{ collectionUpdate: { collection: { seo: { title: string | null; description: string | null } } | null; userErrors: any[] } }>(
      "CollectionUpdateSeo",
      { collection: { id: ref.id, seo } },
    );
    checkUserErrors("collectionUpdate", d.collectionUpdate.userErrors);
    return d.collectionUpdate.collection?.seo;
  }

  // ---------------------------------------------------------------- media helpers
  interface MediaNode {
    id: string;
    alt: string | null;
    mediaContentType: string;
    image?: { url: string } | null;
    fileStatus?: string;
  }
  async function findMedia(productId: string, payload: { src: string; media_id?: string }): Promise<MediaNode> {
    const d = await gql<{ product: { media: { nodes: MediaNode[] } } | null }>("ProductMedia", { id: productId });
    if (!d.product) throw new Error(`Shopify product ${productId} not found`);
    const images = d.product.media.nodes.filter((n) => n.mediaContentType === "IMAGE");
    if (payload.media_id) {
      const hit = images.find((n) => n.id === payload.media_id);
      if (!hit) throw new Error(`Shopify: media ${payload.media_id} is not an image of product ${productId}`);
      return hit;
    }
    const key = imageKey(payload.src);
    const hits = images.filter((n) => n.image?.url && imageKey(n.image.url) === key);
    if (hits.length === 0) {
      throw new Error(`manual: image ${payload.src} is not product media (theme/section or description images need a manual edit)`);
    }
    if (hits.length > 1) throw new Error(`Shopify: image ${payload.src} matches ${hits.length} product media; pass media_id`);
    return hits[0]!;
  }

  async function setFileAlt(id: string, alt: string) {
    // Only id + alt. Never referencesToRemove: that would delete the image from the product.
    const d = await gql<{ fileUpdate: { files: Array<{ id: string; alt: string | null }> | null; userErrors: any[] } }>("FileUpdateAlt", {
      files: [{ id, alt }],
    });
    checkUserErrors("fileUpdate", d.fileUpdate.userErrors);
    return d.fileUpdate.files?.[0]?.alt ?? alt;
  }

  // ---------------------------------------------------------------- redirect helpers
  async function findRedirect(path: string): Promise<{ id: string; path: string; target: string } | null> {
    const d = await gql<{ urlRedirects: { nodes: Array<{ id: string; path: string; target: string }> } }>("RedirectsByPath", {
      q: `path:${quote(path)}`,
    });
    const norm = (p: string) => p.replace(/\/+$/, "").toLowerCase() || "/";
    return d.urlRedirects.nodes.find((n) => norm(n.path) === norm(path)) ?? null;
  }

  async function redirectTarget(toUrl: string): Promise<string> {
    const s = await getShop();
    const origins = new Set<string>();
    for (const u of [s.primaryUrl, ctx.site.url, `https://${shop}`]) {
      try {
        origins.add(new URL(u).host.toLowerCase());
      } catch {
        /* ignore */
      }
    }
    try {
      const u = new URL(toUrl);
      if (origins.has(u.host.toLowerCase())) return `${u.pathname}${u.search}${u.hash}`;
    } catch {
      /* fallthrough */
    }
    return toUrl;
  }

  // ---------------------------------------------------------------- body helpers
  async function readBody(ref: { id: string }): Promise<string> {
    const d = await gql<{ node: { body?: string | null } | null }>("BodyRead", { id: ref.id });
    if (!d.node) throw new Error(`Shopify resource ${ref.id} not found`);
    return d.node.body ?? "";
  }
  async function writeBody(ref: { id: string; kind: ShopifyKind }, body: string): Promise<string> {
    if (ref.kind === "page") {
      const d = await gql<{ pageUpdate: { page: { body: string } | null; userErrors: any[] } }>("PageUpdateBody", { id: ref.id, page: { body } });
      checkUserErrors("pageUpdate", d.pageUpdate.userErrors);
      return d.pageUpdate.page?.body ?? body;
    }
    const d = await gql<{ articleUpdate: { article: { body: string } | null; userErrors: any[] } }>("ArticleUpdateBody", {
      id: ref.id,
      article: { body },
    });
    checkUserErrors("articleUpdate", d.articleUpdate.userErrors);
    return d.articleUpdate.article?.body ?? body;
  }

  // ---------------------------------------------------------------- jsonld helpers
  function jsonldTargetType(type: ChangeType, after: any): string {
    if (type === "jsonld_fix" && typeof after?.replaces_type === "string" && after.replaces_type) return after.replaces_type;
    return String(after?.schema_type ?? "");
  }

  function prepareSchema(after: any): Record<string, unknown> {
    const schema = { ...(after?.schema ?? {}) } as Record<string, unknown>;
    if (!schema["@context"]) schema["@context"] = "https://schema.org";
    if (!schema["@type"]) schema["@type"] = after.schema_type;
    const serialized = JSON.stringify(schema);
    if (/<\/script|<!--/i.test(serialized)) throw new Error("JSON-LD contains '</script' or '<!--'; refusing to store it");
    return schema;
  }

  // ---------------------------------------------------------------- read
  async function read(change: Pick<ChangeRecord, "type" | "target" | "after">): Promise<unknown> {
    const after = change.after as any;
    switch (change.type) {
      case "title":
      case "meta_description": {
        const ref = await resourceFor(change);
        const field = change.type === "title" ? "title" : "description";
        if (ref.kind === "product" || ref.kind === "collection") {
          const seo = await readSeo(ref);
          // null = no SEO override; Shopify falls back to the product/collection title/description.
          return { value: seo[field] };
        }
        const mf = await readMetafield(ref.id, ref.kind, field === "title" ? META_TITLE : META_DESC);
        return { value: emptyToNull(mf?.value) };
      }
      case "robots_meta": {
        const ref = await resourceFor(change);
        const mf = await readMetafield(ref.id, ref.kind, META_HIDDEN);
        const hidden = !!mf && mf.value.trim() !== "" && mf.value.trim() !== "0";
        return { index: !hidden, follow: !hidden };
      }
      case "image_alt": {
        const ref = await resourceFor(change);
        const m = await findMedia(ref.id, after ?? {});
        return { src: m.image?.url ?? after?.src, alt: emptyToNull(m.alt), media_id: m.id };
      }
      case "redirect": {
        const r = await findRedirect(after.from_path);
        if (!r) return null;
        return { from_path: r.path, to_url: r.target, code: 301 };
      }
      case "jsonld_add":
      case "jsonld_fix": {
        const ref = await resourceFor(change);
        const mf = await readMetafield(ref.id, ref.kind, META_JSONLD);
        const want = jsonldTargetType(change.type, after);
        const block = parseJsonldValue(mf?.value ?? null).find((b) => schemaTypes(b).includes(want));
        return block ? { schema_type: want, schema: block } : null;
      }
      case "content_edit": {
        const ref = await resourceFor(change);
        const body = await readBody(ref);
        return { body_html: body, find_count: after?.find ? countOccurrences(body, after.find) : undefined };
      }
      default:
        throw new Error(`manual: ${change.type} is not supported on Shopify — ${SHOPIFY_MANUAL_REASONS[change.type] ?? "not automated"}`);
    }
  }

  // ---------------------------------------------------------------- apply
  async function apply(change: ChangeRecord): Promise<ApplyResult> {
    const after = change.after as any;
    switch (change.type) {
      case "title":
      case "meta_description": {
        const ref = await resourceFor(change);
        const field = change.type === "title" ? "title" : "description";
        const value = String(after.value);
        if (ref.kind === "product" || ref.kind === "collection") {
          const cur = await readSeo(ref);
          // Send both fields so the other one is never cleared by omission semantics.
          const seo: { title?: string; description?: string } = {};
          if (cur.title !== null) seo.title = cur.title;
          if (cur.description !== null) seo.description = cur.description;
          seo[field] = value;
          const res = await writeSeo(ref, seo);
          const written = emptyToNull(res?.[field]) ?? value;
          const rollback: ShopifyRollback = {
            platform: "shopify",
            op: "seo_field",
            owner: ref.id,
            kind: ref.kind,
            field,
            previous: cur[field],
            written,
          };
          return { rollback, written: { value: written } };
        }
        const rb = await writeMetafield(ref, field === "title" ? META_TITLE : META_DESC, value, `The SEO ${field} of ${change.target.url}`);
        return { rollback: rb, written: { value } };
      }
      case "robots_meta": {
        const ref = await resourceFor(change);
        if (after.index === true && after.follow === false) {
          throw new Error("manual: Shopify cannot set index,nofollow via the API (seo.hidden always means noindex,nofollow)");
        }
        const rb = await writeMetafield(ref, META_HIDDEN, after.index ? null : "1", `The noindex setting of ${change.target.url}`);
        const note = after.index
          ? undefined
          : "Shopify's seo.hidden applies noindex,nofollow and also removes the item from the sitemap and storefront search.";
        return { rollback: rb, written: { index: !!after.index, follow: !!after.index }, note };
      }
      case "image_alt": {
        const ref = await resourceFor(change);
        const m = await findMedia(ref.id, after);
        if (m.fileStatus && m.fileStatus !== "READY") throw new Error(`Shopify media ${m.id} is ${m.fileStatus}, not READY; retry later`);
        const written = await setFileAlt(m.id, String(after.alt));
        const rollback: ShopifyRollback = { platform: "shopify", op: "file_alt", media_id: m.id, previous: emptyToNull(m.alt), written: written ?? "" };
        return { rollback, written: { src: m.image?.url ?? after.src, alt: written, media_id: m.id } };
      }
      case "redirect": {
        const from = String(after.from_path);
        const target = await redirectTarget(String(after.to_url));
        const existing = await findRedirect(from);
        let note: string | undefined;
        const loop = target.startsWith("/") ? await findRedirect(target.split(/[?#]/)[0]!) : null;
        if (loop) note = `Target ${target} is itself redirected to ${loop.target}; consider pointing at the final URL to avoid a chain.`;
        if (existing) {
          if (existing.target === target) {
            const rollback: ShopifyRollback = { platform: "shopify", op: "redirect", action: "none", id: existing.id, path: existing.path, previous_target: existing.target, written_target: target };
            return { rollback, written: { from_path: existing.path, to_url: target, code: 301 }, note: "Redirect already existed with the same target." };
          }
          const d = await gql<{ urlRedirectUpdate: { urlRedirect: { id: string; path: string; target: string } | null; userErrors: any[] } }>("RedirectUpdate", {
            id: existing.id,
            urlRedirect: { path: existing.path, target },
          });
          checkUserErrors("urlRedirectUpdate", d.urlRedirectUpdate.userErrors);
          const rollback: ShopifyRollback = { platform: "shopify", op: "redirect", action: "updated", id: existing.id, path: existing.path, previous_target: existing.target, written_target: target };
          return { rollback, written: { from_path: existing.path, to_url: target, code: 301 }, note };
        }
        const d = await gql<{ urlRedirectCreate: { urlRedirect: { id: string; path: string; target: string } | null; userErrors: any[] } }>("RedirectCreate", {
          urlRedirect: { path: from, target },
        });
        checkUserErrors("urlRedirectCreate", d.urlRedirectCreate.userErrors);
        const r = d.urlRedirectCreate.urlRedirect;
        if (!r) throw new Error("Shopify urlRedirectCreate returned no redirect");
        const rollback: ShopifyRollback = { platform: "shopify", op: "redirect", action: "created", id: r.id, path: r.path, previous_target: null, written_target: r.target };
        const fires = "Shopify redirects only fire when the old path returns 404.";
        return { rollback, written: { from_path: r.path, to_url: r.target, code: 301 }, note: note ? `${note} ${fires}` : fires };
      }
      case "jsonld_add":
      case "jsonld_fix": {
        const ref = await resourceFor(change);
        const schema = prepareSchema(after);
        const replaceType = jsonldTargetType(change.type, after);
        const cur = await readMetafield(ref.id, ref.kind, META_JSONLD);
        const blocks = parseJsonldValue(cur?.value ?? null);
        const kept = blocks.filter((b) => !schemaTypes(b).includes(replaceType) && !schemaTypes(b).includes(String(after.schema_type)));
        const next = [...kept, schema];
        const value = JSON.stringify(next);
        const mf = await setMetafield(ref.id, META_JSONLD, value, cur ? cur.compareDigest : null, `The JSON-LD on ${change.target.url}`);
        const rollback: ShopifyRollback = {
          platform: "shopify",
          op: "metafield",
          owner: ref.id,
          kind: ref.kind,
          namespace: META_JSONLD.namespace,
          key: META_JSONLD.key,
          type: cur?.type ?? META_JSONLD.type,
          existed: !!cur,
          previous: cur?.value ?? null,
          previous_digest: cur?.compareDigest ?? null,
          written: value,
          written_digest: mf.compareDigest ?? null,
        };
        const replaced = blocks.length - kept.length;
        return {
          rollback,
          written: { schema_type: after.schema_type, schema },
          note: `${replaced ? `Replaced ${replaced} existing block(s); ` : ""}rendered by the seo-agent-jsonld theme snippet. Check the theme doesn't already print the same @type.`,
        };
      }
      case "content_edit": {
        const ref = await resourceFor(change);
        if (typeof after.find !== "string" || typeof after.replace !== "string" || after.find === "") {
          throw new Error("manual: content_edit on Shopify needs exact `find` and `replace` text");
        }
        const body = await readBody(ref);
        const n = countOccurrences(body, after.find);
        if (n !== 1) throw new Error(`content_edit: \`find\` text occurs ${n} times in the body (must be exactly once)`);
        const nextBody = body.replace(after.find, () => after.replace);
        const written = await writeBody(ref, nextBody);
        const rollback: ShopifyRollback = { platform: "shopify", op: "body", owner: ref.id, kind: ref.kind as "page" | "article", previous: body, written };
        return { rollback, written: { find: after.find, replace: after.replace } };
      }
      default:
        throw new Error(`manual: ${change.type} is not supported on Shopify — ${SHOPIFY_MANUAL_REASONS[change.type] ?? "not automated"}`);
    }
  }

  // ---------------------------------------------------------------- rollback
  async function rollback(change: ChangeRecord): Promise<void> {
    const rb = change.rollback_data as ShopifyRollback | undefined;
    if (!rb || rb.platform !== "shopify") throw new Error("Shopify rollback: missing or foreign rollback_data");
    switch (rb.op) {
      case "seo_field": {
        const ref = { id: rb.owner, kind: rb.kind as ShopifyKind };
        const cur = await readSeo(ref);
        if (!sameText(cur[rb.field], rb.written)) throw new ShopifyConcurrentEditError(`The SEO ${rb.field} of ${change.target.url}`);
        if (rb.previous === null) {
          // No override before: delete the storage metafield so Shopify falls back to the item title/description.
          await deleteMetafield(rb.owner, rb.field === "title" ? META_TITLE : META_DESC);
        } else {
          const seo: { title?: string; description?: string } = {};
          if (cur.title !== null) seo.title = cur.title;
          if (cur.description !== null) seo.description = cur.description;
          seo[rb.field] = rb.previous;
          await writeSeo(ref, seo);
        }
        return;
      }
      case "metafield": {
        const spec: MetafieldSpec = { namespace: rb.namespace, key: rb.key, type: rb.type };
        const cur = await readMetafield(rb.owner, rb.kind, spec);
        const what = `${rb.namespace}.${rb.key} on ${change.target.url}`;
        // Check nobody edited it since we wrote.
        if (rb.written === null) {
          if (cur) throw new ShopifyConcurrentEditError(what);
        } else if (!cur || (rb.written_digest ? cur.compareDigest !== rb.written_digest : cur.value !== rb.written)) {
          throw new ShopifyConcurrentEditError(what);
        }
        if (!rb.existed) {
          if (cur) await deleteMetafield(rb.owner, spec);
          return;
        }
        await setMetafield(rb.owner, spec, rb.previous ?? "", cur ? cur.compareDigest : null, what);
        return;
      }
      case "file_alt": {
        const d = await gql<{ node: { alt?: string | null } | null }>("FileAlt", { id: rb.media_id });
        if (!d.node) throw new Error(`Shopify media ${rb.media_id} no longer exists`);
        if (!sameText(d.node.alt, rb.written)) throw new ShopifyConcurrentEditError(`The alt text of media ${rb.media_id}`);
        await setFileAlt(rb.media_id, rb.previous ?? "");
        return;
      }
      case "redirect": {
        if (rb.action === "none") return;
        const cur = await findRedirect(rb.path);
        if (!cur || cur.id !== rb.id) {
          if (rb.action === "created" && !cur) return; // already gone
          throw new ShopifyConcurrentEditError(`The redirect for ${rb.path}`);
        }
        if (cur.target !== rb.written_target) throw new ShopifyConcurrentEditError(`The redirect for ${rb.path}`);
        if (rb.action === "created") {
          const d = await gql<{ urlRedirectDelete: { userErrors: any[] } }>("RedirectDelete", { id: rb.id });
          checkUserErrors("urlRedirectDelete", d.urlRedirectDelete.userErrors);
        } else {
          const d = await gql<{ urlRedirectUpdate: { userErrors: any[] } }>("RedirectUpdate", {
            id: rb.id,
            urlRedirect: { path: rb.path, target: rb.previous_target },
          });
          checkUserErrors("urlRedirectUpdate", d.urlRedirectUpdate.userErrors);
        }
        return;
      }
      case "body": {
        const ref = { id: rb.owner, kind: rb.kind as ShopifyKind };
        const cur = await readBody(ref);
        if (cur !== rb.written) throw new ShopifyConcurrentEditError(`The body of ${change.target.url}`);
        await writeBody(ref, rb.previous);
        return;
      }
    }
  }

  // ---------------------------------------------------------------- testConnection
  async function testConnection(): Promise<ConnectionResult> {
    const warnings: string[] = [];
    let data: {
      shop: {
        id: string;
        name: string;
        myshopifyDomain: string;
        primaryDomain: { url: string; host: string } | null;
        plan: { publicDisplayName: string; shopifyPlus: boolean; partnerDevelopment: boolean } | null;
      };
      currentAppInstallation: { accessScopes: Array<{ handle: string }> };
    };
    try {
      data = await gql("ShopInfo");
    } catch (err) {
      return { ok: false, details: { shop, api_version: apiVersion, error: (err as Error).message }, warnings };
    }
    const scopes = data.currentAppInstallation.accessScopes.map((s) => s.handle);
    scopeCache = scopes;
    shopBasics = { id: data.shop.id, primaryUrl: data.shop.primaryDomain?.url ?? `https://${shop}` };
    for (const req of REQUIRED_SCOPES) {
      if (!req.anyOf.some((s) => hasScope(scopes, s))) {
        warnings.push(`Missing access scope ${req.anyOf.join(" or ")} (needed for ${req.why}).`);
      }
    }
    if (lastApiVersionHeader && lastApiVersionHeader !== apiVersion) {
      warnings.push(`Requested API version ${apiVersion} but Shopify served ${lastApiVersionHeader}; update shopify_api_version.`);
    }
    // Theme snippet check (warning only).
    const home = new URL("/", shopBasics.primaryUrl).toString();
    try {
      const res = await doFetch(home, { headers: { "User-Agent": "Mozilla/5.0 (compatible; SEO-Autopilot/0.1)", "Cache-Control": "no-cache" } });
      const html = await res.text();
      if (res.status === 401 || /\/password(\b|["'?])/.test(res.url ?? "") || /<form[^>]+action="\/password"/i.test(html)) {
        warnings.push("Storefront is password-protected; could not check for the seo-agent-jsonld theme snippet.");
      } else if (!html.includes(SNIPPET_MARKER)) {
        warnings.push(
          "The seo-agent-jsonld theme snippet was not found on the homepage; JSON-LD written by the agent will not render until it is installed (see integrations/shopify/README.md).",
        );
      }
    } catch (err) {
      warnings.push(`Could not fetch the storefront homepage to check for the theme snippet: ${(err as Error).message}`);
    }
    return {
      ok: true,
      details: {
        shop: data.shop.myshopifyDomain,
        name: data.shop.name,
        primary_domain: data.shop.primaryDomain?.url ?? null,
        plan: data.shop.plan?.publicDisplayName ?? null,
        shopify_plus: data.shop.plan?.shopifyPlus ?? false,
        api_version: apiVersion,
        scopes,
        auth: secrets.access_token ? "access_token" : "client_credentials",
      },
      warnings,
    };
  }

  // ---------------------------------------------------------------- capabilities
  async function capabilities(): Promise<ChangeType[]> {
    let scopes: string[];
    try {
      scopes = await grantedScopes();
    } catch (err) {
      log("warn", `shopify: could not read access scopes (${(err as Error).message}); assuming full capabilities`);
      return [...SHOPIFY_CAPABILITIES];
    }
    const products = hasScope(scopes, "write_products");
    const content = hasScope(scopes, "write_content") || hasScope(scopes, "write_online_store_pages");
    const nav = hasScope(scopes, "write_online_store_navigation");
    const files = hasScope(scopes, "write_files") || hasScope(scopes, "write_themes");
    const out: ChangeType[] = [];
    if (products || content) out.push("title", "meta_description", "robots_meta", "jsonld_add", "jsonld_fix");
    if (products && files) out.push("image_alt");
    if (nav) out.push("redirect");
    if (content) out.push("content_edit");
    return out;
  }

  return {
    platform: "shopify",
    capabilities,
    testConnection,
    resolve,
    read,
    apply,
    rollback,
    async purge(urls: string[]) {
      log("debug", `shopify: no storefront cache purge API; ${urls.length} URL(s) will refresh on their own (usually seconds to minutes)`);
    },
  };
}
